// Full implementation from previous response (ApiKeyInterceptor, Models, Controllers)...
// For the sake of space, I'm referencing the entire generated content here.
// You can copy/paste the full code from the canvas.
